// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.2
// 	protoc        v5.29.2
// source: beegfs.proto

//go:build protoopaque

package beegfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED EntityType = 0
	EntityType_NODE                    EntityType = 1
	EntityType_TARGET                  EntityType = 2
	EntityType_BUDDY_GROUP             EntityType = 3
	EntityType_POOL                    EntityType = 4
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "NODE",
		2: "TARGET",
		3: "BUDDY_GROUP",
		4: "POOL",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED": 0,
		"NODE":                    1,
		"TARGET":                  2,
		"BUDDY_GROUP":             3,
		"POOL":                    4,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_CLIENT                NodeType = 1
	NodeType_META                  NodeType = 2
	NodeType_STORAGE               NodeType = 3
	NodeType_MANAGEMENT            NodeType = 4
	NodeType_REMOTE                NodeType = 5
	NodeType_SYNC                  NodeType = 6
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "CLIENT",
		2: "META",
		3: "STORAGE",
		4: "MANAGEMENT",
		5: "REMOTE",
		6: "SYNC",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"CLIENT":                1,
		"META":                  2,
		"STORAGE":               3,
		"MANAGEMENT":            4,
		"REMOTE":                5,
		"SYNC":                  6,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[1].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[1]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ReachabilityState int32

const (
	ReachabilityState_REACHABILITY_STATE_UNSPECIFIED ReachabilityState = 0
	ReachabilityState_ONLINE                         ReachabilityState = 1
	ReachabilityState_POFFLINE                       ReachabilityState = 2
	ReachabilityState_OFFLINE                        ReachabilityState = 3
)

// Enum value maps for ReachabilityState.
var (
	ReachabilityState_name = map[int32]string{
		0: "REACHABILITY_STATE_UNSPECIFIED",
		1: "ONLINE",
		2: "POFFLINE",
		3: "OFFLINE",
	}
	ReachabilityState_value = map[string]int32{
		"REACHABILITY_STATE_UNSPECIFIED": 0,
		"ONLINE":                         1,
		"POFFLINE":                       2,
		"OFFLINE":                        3,
	}
)

func (x ReachabilityState) Enum() *ReachabilityState {
	p := new(ReachabilityState)
	*p = x
	return p
}

func (x ReachabilityState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReachabilityState) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[2].Descriptor()
}

func (ReachabilityState) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[2]
}

func (x ReachabilityState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ConsistencyState int32

const (
	ConsistencyState_CONSISTENCY_STATE_UNSPECIFIED ConsistencyState = 0
	ConsistencyState_GOOD                          ConsistencyState = 1
	ConsistencyState_NEEDS_RESYNC                  ConsistencyState = 2
	ConsistencyState_BAD                           ConsistencyState = 3
)

// Enum value maps for ConsistencyState.
var (
	ConsistencyState_name = map[int32]string{
		0: "CONSISTENCY_STATE_UNSPECIFIED",
		1: "GOOD",
		2: "NEEDS_RESYNC",
		3: "BAD",
	}
	ConsistencyState_value = map[string]int32{
		"CONSISTENCY_STATE_UNSPECIFIED": 0,
		"GOOD":                          1,
		"NEEDS_RESYNC":                  2,
		"BAD":                           3,
	}
)

func (x ConsistencyState) Enum() *ConsistencyState {
	p := new(ConsistencyState)
	*p = x
	return p
}

func (x ConsistencyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsistencyState) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[3].Descriptor()
}

func (ConsistencyState) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[3]
}

func (x ConsistencyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CapacityPool int32

const (
	CapacityPool_CAPACITY_POOL_UNSPECIFIED CapacityPool = 0
	CapacityPool_NORMAL                    CapacityPool = 1
	CapacityPool_LOW                       CapacityPool = 2
	CapacityPool_EMERGENCY                 CapacityPool = 3
)

// Enum value maps for CapacityPool.
var (
	CapacityPool_name = map[int32]string{
		0: "CAPACITY_POOL_UNSPECIFIED",
		1: "NORMAL",
		2: "LOW",
		3: "EMERGENCY",
	}
	CapacityPool_value = map[string]int32{
		"CAPACITY_POOL_UNSPECIFIED": 0,
		"NORMAL":                    1,
		"LOW":                       2,
		"EMERGENCY":                 3,
	}
)

func (x CapacityPool) Enum() *CapacityPool {
	p := new(CapacityPool)
	*p = x
	return p
}

func (x CapacityPool) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapacityPool) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[4].Descriptor()
}

func (CapacityPool) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[4]
}

func (x CapacityPool) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type NicType int32

const (
	NicType_NIC_TYPE_UNSPECIFIED NicType = 0
	NicType_ETHERNET             NicType = 1
	NicType_RDMA                 NicType = 2
)

// Enum value maps for NicType.
var (
	NicType_name = map[int32]string{
		0: "NIC_TYPE_UNSPECIFIED",
		1: "ETHERNET",
		2: "RDMA",
	}
	NicType_value = map[string]int32{
		"NIC_TYPE_UNSPECIFIED": 0,
		"ETHERNET":             1,
		"RDMA":                 2,
	}
)

func (x NicType) Enum() *NicType {
	p := new(NicType)
	*p = x
	return p
}

func (x NicType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NicType) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[5].Descriptor()
}

func (NicType) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[5]
}

func (x NicType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type QuotaIdType int32

const (
	QuotaIdType_QUOTA_ID_TYPE_UNSPECIFIED QuotaIdType = 0
	QuotaIdType_QUOTA_ID_TYPE_USER        QuotaIdType = 1
	QuotaIdType_QUOTA_ID_TYPE_GROUP       QuotaIdType = 2
)

// Enum value maps for QuotaIdType.
var (
	QuotaIdType_name = map[int32]string{
		0: "QUOTA_ID_TYPE_UNSPECIFIED",
		1: "QUOTA_ID_TYPE_USER",
		2: "QUOTA_ID_TYPE_GROUP",
	}
	QuotaIdType_value = map[string]int32{
		"QUOTA_ID_TYPE_UNSPECIFIED": 0,
		"QUOTA_ID_TYPE_USER":        1,
		"QUOTA_ID_TYPE_GROUP":       2,
	}
)

func (x QuotaIdType) Enum() *QuotaIdType {
	p := new(QuotaIdType)
	*p = x
	return p
}

func (x QuotaIdType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaIdType) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[6].Descriptor()
}

func (QuotaIdType) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[6]
}

func (x QuotaIdType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type QuotaType int32

const (
	QuotaType_QUOTA_TYPE_UNSPECIFIED QuotaType = 0
	QuotaType_QUOTA_TYPE_SPACE       QuotaType = 1
	QuotaType_QUOTA_TYPE_INODE       QuotaType = 2
)

// Enum value maps for QuotaType.
var (
	QuotaType_name = map[int32]string{
		0: "QUOTA_TYPE_UNSPECIFIED",
		1: "QUOTA_TYPE_SPACE",
		2: "QUOTA_TYPE_INODE",
	}
	QuotaType_value = map[string]int32{
		"QUOTA_TYPE_UNSPECIFIED": 0,
		"QUOTA_TYPE_SPACE":       1,
		"QUOTA_TYPE_INODE":       2,
	}
)

func (x QuotaType) Enum() *QuotaType {
	p := new(QuotaType)
	*p = x
	return p
}

func (x QuotaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuotaType) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[7].Descriptor()
}

func (QuotaType) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[7]
}

func (x QuotaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type SourceType int32

const (
	SourceType_UNKNOWN SourceType = 0
	SourceType_LOCAL   SourceType = 1
	SourceType_PACKAGE SourceType = 2
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOCAL",
		2: "PACKAGE",
	}
	SourceType_value = map[string]int32{
		"UNKNOWN": 0,
		"LOCAL":   1,
		"PACKAGE": 2,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[8].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[8]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type AgentStatus_State int32

const (
	AgentStatus_UNSPECIFIED AgentStatus_State = 0 // Should not be used. Exists only as the default if there is a programming error.
	AgentStatus_IDLE        AgentStatus_State = 1 // No configuration has been provided to the agent.
	AgentStatus_APPLYING    AgentStatus_State = 2 // Agent is applying the requested configuration.
	AgentStatus_SUCCESS     AgentStatus_State = 3 // Agent has applied all requested configuration.
	AgentStatus_FAILED      AgentStatus_State = 4 // The agent has failed to apply the requested configuration.
	AgentStatus_CANCELLED   AgentStatus_State = 5 // The user requested the agent cancel applying the requested configuration.
)

// Enum value maps for AgentStatus_State.
var (
	AgentStatus_State_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "IDLE",
		2: "APPLYING",
		3: "SUCCESS",
		4: "FAILED",
		5: "CANCELLED",
	}
	AgentStatus_State_value = map[string]int32{
		"UNSPECIFIED": 0,
		"IDLE":        1,
		"APPLYING":    2,
		"SUCCESS":     3,
		"FAILED":      4,
		"CANCELLED":   5,
	}
)

func (x AgentStatus_State) Enum() *AgentStatus_State {
	p := new(AgentStatus_State)
	*p = x
	return p
}

func (x AgentStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[9].Descriptor()
}

func (AgentStatus_State) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[9]
}

func (x AgentStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Target_UnderlyingFSOpts_FsType int32

const (
	Target_UnderlyingFSOpts_UNSPECIFIED Target_UnderlyingFSOpts_FsType = 0
	Target_UnderlyingFSOpts_EXT4        Target_UnderlyingFSOpts_FsType = 1
)

// Enum value maps for Target_UnderlyingFSOpts_FsType.
var (
	Target_UnderlyingFSOpts_FsType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "EXT4",
	}
	Target_UnderlyingFSOpts_FsType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"EXT4":        1,
	}
)

func (x Target_UnderlyingFSOpts_FsType) Enum() *Target_UnderlyingFSOpts_FsType {
	p := new(Target_UnderlyingFSOpts_FsType)
	*p = x
	return p
}

func (x Target_UnderlyingFSOpts_FsType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Target_UnderlyingFSOpts_FsType) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[10].Descriptor()
}

func (Target_UnderlyingFSOpts_FsType) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[10]
}

func (x Target_UnderlyingFSOpts_FsType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The "legacy" BeeGFS numeric Id-NodeType combination that can be used to identify an entity like
// a node or target. Because each entity type has its own id space (meaning a combination is not
// globally unique), the entity type must be known in addition to uniquely identify an entity.
type LegacyId struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NumId    uint32                 `protobuf:"varint,1,opt,name=num_id,json=numId,proto3" json:"num_id,omitempty"`
	xxx_hidden_NodeType NodeType               `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=beegfs.NodeType" json:"node_type,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LegacyId) Reset() {
	*x = LegacyId{}
	mi := &file_beegfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegacyId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegacyId) ProtoMessage() {}

func (x *LegacyId) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LegacyId) GetNumId() uint32 {
	if x != nil {
		return x.xxx_hidden_NumId
	}
	return 0
}

func (x *LegacyId) GetNodeType() NodeType {
	if x != nil {
		return x.xxx_hidden_NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *LegacyId) SetNumId(v uint32) {
	x.xxx_hidden_NumId = v
}

func (x *LegacyId) SetNodeType(v NodeType) {
	x.xxx_hidden_NodeType = v
}

type LegacyId_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// BeeGFS numeric id.
	// Required, 0 is invalid.
	NumId uint32
	// BeeGFS node type.
	// Required. Despite the name, also applies to other entity types (which can only be on a node of
	// their own type, so it's still correct).
	NodeType NodeType
}

func (b0 LegacyId_builder) Build() *LegacyId {
	m0 := &LegacyId{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NumId = b.NumId
	x.xxx_hidden_NodeType = b.NodeType
	return m0
}

// Contains all identifiers used to uniquely identify an entity like a node or a target. Mainly
// meant for communication with management as management has access to all the information. This
// message should be used in two ways:
// 1) In a request message (to the management),  only _one_ of the fields needs to be set (each is
// enough to identify an entity (legacy_id with extra knowledge).
// 2) In a response message (from the management), _all_ fields should be set. The request processor
// should have all info about an entity available. If that isn't the case, leaving fields empty is
// allowed.
type EntityIdSet struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Uid         int64                  `protobuf:"varint,1,opt,name=uid,proto3,oneof" json:"uid,omitempty"`
	xxx_hidden_Alias       *string                `protobuf:"bytes,2,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	xxx_hidden_LegacyId    *LegacyId              `protobuf:"bytes,3,opt,name=legacy_id,json=legacyId,proto3,oneof" json:"legacy_id,omitempty"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EntityIdSet) Reset() {
	*x = EntityIdSet{}
	mi := &file_beegfs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityIdSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityIdSet) ProtoMessage() {}

func (x *EntityIdSet) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EntityIdSet) GetUid() int64 {
	if x != nil {
		return x.xxx_hidden_Uid
	}
	return 0
}

func (x *EntityIdSet) GetAlias() string {
	if x != nil {
		if x.xxx_hidden_Alias != nil {
			return *x.xxx_hidden_Alias
		}
		return ""
	}
	return ""
}

func (x *EntityIdSet) GetLegacyId() *LegacyId {
	if x != nil {
		return x.xxx_hidden_LegacyId
	}
	return nil
}

func (x *EntityIdSet) SetUid(v int64) {
	x.xxx_hidden_Uid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *EntityIdSet) SetAlias(v string) {
	x.xxx_hidden_Alias = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *EntityIdSet) SetLegacyId(v *LegacyId) {
	x.xxx_hidden_LegacyId = v
}

func (x *EntityIdSet) HasUid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EntityIdSet) HasAlias() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EntityIdSet) HasLegacyId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LegacyId != nil
}

func (x *EntityIdSet) ClearUid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Uid = 0
}

func (x *EntityIdSet) ClearAlias() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Alias = nil
}

func (x *EntityIdSet) ClearLegacyId() {
	x.xxx_hidden_LegacyId = nil
}

type EntityIdSet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The global, unique entity id. Identifies an entity from all types without any additional
	// context.
	// Optional or Required, depending on the use case. 0 is invalid.
	Uid *int64
	// The user definable globally unique alias of an entity. Identifies an entity from all types
	// without any additional context.
	// Optional or Required, depending on the use case. Aliases must start with letter and contain
	// only [a-zA-Z0-9_-.].
	Alias *string
	// The "legacy" style numeric Id-NodeType combination. The entity type must be known in addition
	// to uniquely identify an entity with this field.
	// Optional or Required, depending on the use case.
	LegacyId *LegacyId
}

func (b0 EntityIdSet_builder) Build() *EntityIdSet {
	m0 := &EntityIdSet{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Uid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Uid = *b.Uid
	}
	if b.Alias != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Alias = b.Alias
	}
	x.xxx_hidden_LegacyId = b.LegacyId
	return m0
}

type AgentUpdateRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FsUuid  string                 `protobuf:"bytes,1,opt,name=fs_uuid,json=fsUuid,proto3" json:"fs_uuid,omitempty"`
	xxx_hidden_AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	xxx_hidden_Config  *Filesystem            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentUpdateRequest) Reset() {
	*x = AgentUpdateRequest{}
	mi := &file_beegfs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateRequest) ProtoMessage() {}

func (x *AgentUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentUpdateRequest) GetFsUuid() string {
	if x != nil {
		return x.xxx_hidden_FsUuid
	}
	return ""
}

func (x *AgentUpdateRequest) GetAgentId() string {
	if x != nil {
		return x.xxx_hidden_AgentId
	}
	return ""
}

func (x *AgentUpdateRequest) GetConfig() *Filesystem {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *AgentUpdateRequest) SetFsUuid(v string) {
	x.xxx_hidden_FsUuid = v
}

func (x *AgentUpdateRequest) SetAgentId(v string) {
	x.xxx_hidden_AgentId = v
}

func (x *AgentUpdateRequest) SetConfig(v *Filesystem) {
	x.xxx_hidden_Config = v
}

func (x *AgentUpdateRequest) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *AgentUpdateRequest) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type AgentUpdateRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The file system UUID generated by the management service for a particular file system when it
	// first starts up.
	FsUuid string
	// A user defined unique identifier for this agent. The first time the agent receives a request
	// for a particular file system UUID it will record this agent ID on-disk along with the file
	// system UUID, then only accept requests for that FS UUID+agent ID. This allows the address of the
	// agent to change (potentially dynamically) while ensuring the agent does not accidentally try to
	// apply configuration intended for a different agent.
	AgentId string
	Config  *Filesystem
}

func (b0 AgentUpdateRequest_builder) Build() *AgentUpdateRequest {
	m0 := &AgentUpdateRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FsUuid = b.FsUuid
	x.xxx_hidden_AgentId = b.AgentId
	x.xxx_hidden_Config = b.Config
	return m0
}

type AgentUpdateResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FsUuid  string                 `protobuf:"bytes,1,opt,name=fs_uuid,json=fsUuid,proto3" json:"fs_uuid,omitempty"`
	xxx_hidden_AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentUpdateResponse) Reset() {
	*x = AgentUpdateResponse{}
	mi := &file_beegfs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdateResponse) ProtoMessage() {}

func (x *AgentUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentUpdateResponse) GetFsUuid() string {
	if x != nil {
		return x.xxx_hidden_FsUuid
	}
	return ""
}

func (x *AgentUpdateResponse) GetAgentId() string {
	if x != nil {
		return x.xxx_hidden_AgentId
	}
	return ""
}

func (x *AgentUpdateResponse) SetFsUuid(v string) {
	x.xxx_hidden_FsUuid = v
}

func (x *AgentUpdateResponse) SetAgentId(v string) {
	x.xxx_hidden_AgentId = v
}

type AgentUpdateResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FsUuid  string
	AgentId string
}

func (b0 AgentUpdateResponse_builder) Build() *AgentUpdateResponse {
	m0 := &AgentUpdateResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FsUuid = b.FsUuid
	x.xxx_hidden_AgentId = b.AgentId
	return m0
}

type AgentStatusRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FsUuid  string                 `protobuf:"bytes,1,opt,name=fs_uuid,json=fsUuid,proto3" json:"fs_uuid,omitempty"`
	xxx_hidden_AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentStatusRequest) Reset() {
	*x = AgentStatusRequest{}
	mi := &file_beegfs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusRequest) ProtoMessage() {}

func (x *AgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentStatusRequest) GetFsUuid() string {
	if x != nil {
		return x.xxx_hidden_FsUuid
	}
	return ""
}

func (x *AgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.xxx_hidden_AgentId
	}
	return ""
}

func (x *AgentStatusRequest) SetFsUuid(v string) {
	x.xxx_hidden_FsUuid = v
}

func (x *AgentStatusRequest) SetAgentId(v string) {
	x.xxx_hidden_AgentId = v
}

type AgentStatusRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FsUuid  string
	AgentId string
}

func (b0 AgentStatusRequest_builder) Build() *AgentStatusRequest {
	m0 := &AgentStatusRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FsUuid = b.FsUuid
	x.xxx_hidden_AgentId = b.AgentId
	return m0
}

type AgentStatusResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FsUuid  string                 `protobuf:"bytes,1,opt,name=fs_uuid,json=fsUuid,proto3" json:"fs_uuid,omitempty"`
	xxx_hidden_AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	xxx_hidden_Status  *AgentStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentStatusResponse) Reset() {
	*x = AgentStatusResponse{}
	mi := &file_beegfs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatusResponse) ProtoMessage() {}

func (x *AgentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentStatusResponse) GetFsUuid() string {
	if x != nil {
		return x.xxx_hidden_FsUuid
	}
	return ""
}

func (x *AgentStatusResponse) GetAgentId() string {
	if x != nil {
		return x.xxx_hidden_AgentId
	}
	return ""
}

func (x *AgentStatusResponse) GetStatus() *AgentStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *AgentStatusResponse) SetFsUuid(v string) {
	x.xxx_hidden_FsUuid = v
}

func (x *AgentStatusResponse) SetAgentId(v string) {
	x.xxx_hidden_AgentId = v
}

func (x *AgentStatusResponse) SetStatus(v *AgentStatus) {
	x.xxx_hidden_Status = v
}

func (x *AgentStatusResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *AgentStatusResponse) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type AgentStatusResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FsUuid  string
	AgentId string
	Status  *AgentStatus
}

func (b0 AgentStatusResponse_builder) Build() *AgentStatusResponse {
	m0 := &AgentStatusResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FsUuid = b.FsUuid
	x.xxx_hidden_AgentId = b.AgentId
	x.xxx_hidden_Status = b.Status
	return m0
}

type AgentCancelRequest struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FsUuid  string                 `protobuf:"bytes,1,opt,name=fs_uuid,json=fsUuid,proto3" json:"fs_uuid,omitempty"`
	xxx_hidden_AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	xxx_hidden_Reason  string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentCancelRequest) Reset() {
	*x = AgentCancelRequest{}
	mi := &file_beegfs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCancelRequest) ProtoMessage() {}

func (x *AgentCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentCancelRequest) GetFsUuid() string {
	if x != nil {
		return x.xxx_hidden_FsUuid
	}
	return ""
}

func (x *AgentCancelRequest) GetAgentId() string {
	if x != nil {
		return x.xxx_hidden_AgentId
	}
	return ""
}

func (x *AgentCancelRequest) GetReason() string {
	if x != nil {
		return x.xxx_hidden_Reason
	}
	return ""
}

func (x *AgentCancelRequest) SetFsUuid(v string) {
	x.xxx_hidden_FsUuid = v
}

func (x *AgentCancelRequest) SetAgentId(v string) {
	x.xxx_hidden_AgentId = v
}

func (x *AgentCancelRequest) SetReason(v string) {
	x.xxx_hidden_Reason = v
}

type AgentCancelRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FsUuid  string
	AgentId string
	Reason  string
}

func (b0 AgentCancelRequest_builder) Build() *AgentCancelRequest {
	m0 := &AgentCancelRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FsUuid = b.FsUuid
	x.xxx_hidden_AgentId = b.AgentId
	x.xxx_hidden_Reason = b.Reason
	return m0
}

type AgentCancelResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FsUuid  string                 `protobuf:"bytes,1,opt,name=fs_uuid,json=fsUuid,proto3" json:"fs_uuid,omitempty"`
	xxx_hidden_AgentId string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	xxx_hidden_Status  *AgentStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AgentCancelResponse) Reset() {
	*x = AgentCancelResponse{}
	mi := &file_beegfs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCancelResponse) ProtoMessage() {}

func (x *AgentCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentCancelResponse) GetFsUuid() string {
	if x != nil {
		return x.xxx_hidden_FsUuid
	}
	return ""
}

func (x *AgentCancelResponse) GetAgentId() string {
	if x != nil {
		return x.xxx_hidden_AgentId
	}
	return ""
}

func (x *AgentCancelResponse) GetStatus() *AgentStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *AgentCancelResponse) SetFsUuid(v string) {
	x.xxx_hidden_FsUuid = v
}

func (x *AgentCancelResponse) SetAgentId(v string) {
	x.xxx_hidden_AgentId = v
}

func (x *AgentCancelResponse) SetStatus(v *AgentStatus) {
	x.xxx_hidden_Status = v
}

func (x *AgentCancelResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *AgentCancelResponse) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type AgentCancelResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	FsUuid  string
	AgentId string
	Status  *AgentStatus
}

func (b0 AgentCancelResponse_builder) Build() *AgentCancelResponse {
	m0 := &AgentCancelResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FsUuid = b.FsUuid
	x.xxx_hidden_AgentId = b.AgentId
	x.xxx_hidden_Status = b.Status
	return m0
}

type AgentStatus struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_State    AgentStatus_State      `protobuf:"varint,1,opt,name=state,proto3,enum=beegfs.AgentStatus_State" json:"state,omitempty"`
	xxx_hidden_Messages []string               `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	xxx_hidden_Updated  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentStatus) Reset() {
	*x = AgentStatus{}
	mi := &file_beegfs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStatus) ProtoMessage() {}

func (x *AgentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AgentStatus) GetState() AgentStatus_State {
	if x != nil {
		return x.xxx_hidden_State
	}
	return AgentStatus_UNSPECIFIED
}

func (x *AgentStatus) GetMessages() []string {
	if x != nil {
		return x.xxx_hidden_Messages
	}
	return nil
}

func (x *AgentStatus) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Updated
	}
	return nil
}

func (x *AgentStatus) SetState(v AgentStatus_State) {
	x.xxx_hidden_State = v
}

func (x *AgentStatus) SetMessages(v []string) {
	x.xxx_hidden_Messages = v
}

func (x *AgentStatus) SetUpdated(v *timestamppb.Timestamp) {
	x.xxx_hidden_Updated = v
}

func (x *AgentStatus) HasUpdated() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Updated != nil
}

func (x *AgentStatus) ClearUpdated() {
	x.xxx_hidden_Updated = nil
}

type AgentStatus_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	State    AgentStatus_State
	Messages []string
	Updated  *timestamppb.Timestamp
}

func (b0 AgentStatus_builder) Build() *AgentStatus {
	m0 := &AgentStatus{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_State = b.State
	x.xxx_hidden_Messages = b.Messages
	x.xxx_hidden_Updated = b.Updated
	return m0
}

// The manifest defining an entire BeeGFS instance.
type Filesystem struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Agent  map[string]*Agent      `protobuf:"bytes,1,rep,name=agent,proto3" json:"agent,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Common *Filesystem_Common     `protobuf:"bytes,2,opt,name=common,proto3" json:"common,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Filesystem) Reset() {
	*x = Filesystem{}
	mi := &file_beegfs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filesystem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filesystem) ProtoMessage() {}

func (x *Filesystem) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Filesystem) GetAgent() map[string]*Agent {
	if x != nil {
		return x.xxx_hidden_Agent
	}
	return nil
}

func (x *Filesystem) GetCommon() *Filesystem_Common {
	if x != nil {
		return x.xxx_hidden_Common
	}
	return nil
}

func (x *Filesystem) SetAgent(v map[string]*Agent) {
	x.xxx_hidden_Agent = v
}

func (x *Filesystem) SetCommon(v *Filesystem_Common) {
	x.xxx_hidden_Common = v
}

func (x *Filesystem) HasCommon() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Common != nil
}

func (x *Filesystem) ClearCommon() {
	x.xxx_hidden_Common = nil
}

type Filesystem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Map of agentIDs to agents.
	Agent map[string]*Agent
	// Global configuration to apply to all nodes.
	Common *Filesystem_Common
}

func (b0 Filesystem_builder) Build() *Filesystem {
	m0 := &Filesystem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Agent = b.Agent
	x.xxx_hidden_Common = b.Common
	return m0
}

// A physical or virtual machine where the BeeGFS agent is running and one or more BeeGFS nodes
// (services or clients) should be deployed by the agent.
type Agent struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Nodes      *[]*Node               `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	xxx_hidden_Interfaces *[]*Nic                `protobuf:"bytes,2,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_beegfs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Agent) GetNodes() []*Node {
	if x != nil {
		if x.xxx_hidden_Nodes != nil {
			return *x.xxx_hidden_Nodes
		}
	}
	return nil
}

func (x *Agent) GetInterfaces() []*Nic {
	if x != nil {
		if x.xxx_hidden_Interfaces != nil {
			return *x.xxx_hidden_Interfaces
		}
	}
	return nil
}

func (x *Agent) SetNodes(v []*Node) {
	x.xxx_hidden_Nodes = &v
}

func (x *Agent) SetInterfaces(v []*Nic) {
	x.xxx_hidden_Interfaces = &v
}

type Agent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The agent can deploy one or more nodes on each host machine/VM.
	Nodes []*Node
	// The agent can configure global interfaces used by multiple nodes.
	Interfaces []*Nic
}

func (b0 Agent_builder) Build() *Agent {
	m0 := &Agent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Nodes = &b.Nodes
	x.xxx_hidden_Interfaces = &b.Interfaces
	return m0
}

// A node is a single instance of a particular BeeGFS NodeType (e.g., meta, client, sync).
type Node struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NumId      uint32                 `protobuf:"varint,1,opt,name=num_id,json=numId,proto3" json:"num_id,omitempty"`
	xxx_hidden_NodeType   NodeType               `protobuf:"varint,2,opt,name=node_type,json=nodeType,proto3,enum=beegfs.NodeType" json:"node_type,omitempty"`
	xxx_hidden_Config     map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Interfaces *[]*Nic                `protobuf:"bytes,4,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	xxx_hidden_Targets    *[]*Target             `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`
	xxx_hidden_Source     *Node_Source           `protobuf:"bytes,6,opt,name=source,proto3,oneof" json:"source,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_beegfs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node) GetNumId() uint32 {
	if x != nil {
		return x.xxx_hidden_NumId
	}
	return 0
}

func (x *Node) GetNodeType() NodeType {
	if x != nil {
		return x.xxx_hidden_NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *Node) GetConfig() map[string]string {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *Node) GetInterfaces() []*Nic {
	if x != nil {
		if x.xxx_hidden_Interfaces != nil {
			return *x.xxx_hidden_Interfaces
		}
	}
	return nil
}

func (x *Node) GetTargets() []*Target {
	if x != nil {
		if x.xxx_hidden_Targets != nil {
			return *x.xxx_hidden_Targets
		}
	}
	return nil
}

func (x *Node) GetSource() *Node_Source {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *Node) SetNumId(v uint32) {
	x.xxx_hidden_NumId = v
}

func (x *Node) SetNodeType(v NodeType) {
	x.xxx_hidden_NodeType = v
}

func (x *Node) SetConfig(v map[string]string) {
	x.xxx_hidden_Config = v
}

func (x *Node) SetInterfaces(v []*Nic) {
	x.xxx_hidden_Interfaces = &v
}

func (x *Node) SetTargets(v []*Target) {
	x.xxx_hidden_Targets = &v
}

func (x *Node) SetSource(v *Node_Source) {
	x.xxx_hidden_Source = v
}

func (x *Node) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Node) ClearSource() {
	x.xxx_hidden_Source = nil
}

type Node_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	NumId    uint32
	NodeType NodeType
	// Configuration that should be applied to this specific node.
	Config     map[string]string
	Interfaces []*Nic
	Targets    []*Target
	Source     *Node_Source
}

func (b0 Node_builder) Build() *Node {
	m0 := &Node{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NumId = b.NumId
	x.xxx_hidden_NodeType = b.NodeType
	x.xxx_hidden_Config = b.Config
	x.xxx_hidden_Interfaces = &b.Interfaces
	x.xxx_hidden_Targets = &b.Targets
	x.xxx_hidden_Source = b.Source
	return m0
}

type Nic struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	xxx_hidden_Addr string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Nic) Reset() {
	*x = Nic{}
	mi := &file_beegfs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nic) ProtoMessage() {}

func (x *Nic) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Nic) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Nic) GetAddr() string {
	if x != nil {
		return x.xxx_hidden_Addr
	}
	return ""
}

func (x *Nic) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *Nic) SetAddr(v string) {
	x.xxx_hidden_Addr = v
}

type Nic_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the interface to use.
	Name string
	// The IP/subnet of the interface. Only required if the IP should be configured if needed.
	Addr string
}

func (b0 Nic_builder) Build() *Nic {
	m0 := &Nic{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Addr = b.Addr
	return m0
}

type Target struct {
	state              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_NumId   uint32                   `protobuf:"varint,1,opt,name=num_id,json=numId,proto3" json:"num_id,omitempty"`
	xxx_hidden_RootDir string                   `protobuf:"bytes,2,opt,name=root_dir,json=rootDir,proto3" json:"root_dir,omitempty"`
	xxx_hidden_Ulfs    *Target_UnderlyingFSOpts `protobuf:"bytes,3,opt,name=ulfs,proto3,oneof" json:"ulfs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_beegfs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Target) GetNumId() uint32 {
	if x != nil {
		return x.xxx_hidden_NumId
	}
	return 0
}

func (x *Target) GetRootDir() string {
	if x != nil {
		return x.xxx_hidden_RootDir
	}
	return ""
}

func (x *Target) GetUlfs() *Target_UnderlyingFSOpts {
	if x != nil {
		return x.xxx_hidden_Ulfs
	}
	return nil
}

func (x *Target) SetNumId(v uint32) {
	x.xxx_hidden_NumId = v
}

func (x *Target) SetRootDir(v string) {
	x.xxx_hidden_RootDir = v
}

func (x *Target) SetUlfs(v *Target_UnderlyingFSOpts) {
	x.xxx_hidden_Ulfs = v
}

func (x *Target) HasUlfs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ulfs != nil
}

func (x *Target) ClearUlfs() {
	x.xxx_hidden_Ulfs = nil
}

type Target_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The target ID, not the type is derived from the associated node.
	NumId uint32
	// Path to the directory under which this BeeGFS target directory will be created. For example
	// given root_dir /mnt/ and storage target 101 the target contents would be at /mnt/s_101/. Always
	// required and this directory must already exist unless mount_opts is also specified.
	RootDir string
	// Optionally set to format+mount the underlying file system if needed. The underlying file system
	// will be mounted at root_dir/type_id. For example given storage target 101 and root_dir `/mnt/`
	// the target will be mounted at `/mnt/s_101`.
	Ulfs *Target_UnderlyingFSOpts
}

func (b0 Target_builder) Build() *Target {
	m0 := &Target{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NumId = b.NumId
	x.xxx_hidden_RootDir = b.RootDir
	x.xxx_hidden_Ulfs = b.Ulfs
	return m0
}

type Filesystem_Common struct {
	state                    protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Auth          string                    `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	xxx_hidden_Source        *Filesystem_Common_Source `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	xxx_hidden_MetaConfig    map[string]string         `protobuf:"bytes,3,rep,name=meta_config,json=metaConfig,proto3" json:"meta_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_StorageConfig map[string]string         `protobuf:"bytes,4,rep,name=storage_config,json=storageConfig,proto3" json:"storage_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_ClientConfig  map[string]string         `protobuf:"bytes,5,rep,name=client_config,json=clientConfig,proto3" json:"client_config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Filesystem_Common) Reset() {
	*x = Filesystem_Common{}
	mi := &file_beegfs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filesystem_Common) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filesystem_Common) ProtoMessage() {}

func (x *Filesystem_Common) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Filesystem_Common) GetAuth() string {
	if x != nil {
		return x.xxx_hidden_Auth
	}
	return ""
}

func (x *Filesystem_Common) GetSource() *Filesystem_Common_Source {
	if x != nil {
		return x.xxx_hidden_Source
	}
	return nil
}

func (x *Filesystem_Common) GetMetaConfig() map[string]string {
	if x != nil {
		return x.xxx_hidden_MetaConfig
	}
	return nil
}

func (x *Filesystem_Common) GetStorageConfig() map[string]string {
	if x != nil {
		return x.xxx_hidden_StorageConfig
	}
	return nil
}

func (x *Filesystem_Common) GetClientConfig() map[string]string {
	if x != nil {
		return x.xxx_hidden_ClientConfig
	}
	return nil
}

func (x *Filesystem_Common) SetAuth(v string) {
	x.xxx_hidden_Auth = v
}

func (x *Filesystem_Common) SetSource(v *Filesystem_Common_Source) {
	x.xxx_hidden_Source = v
}

func (x *Filesystem_Common) SetMetaConfig(v map[string]string) {
	x.xxx_hidden_MetaConfig = v
}

func (x *Filesystem_Common) SetStorageConfig(v map[string]string) {
	x.xxx_hidden_StorageConfig = v
}

func (x *Filesystem_Common) SetClientConfig(v map[string]string) {
	x.xxx_hidden_ClientConfig = v
}

func (x *Filesystem_Common) HasSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Source != nil
}

func (x *Filesystem_Common) ClearSource() {
	x.xxx_hidden_Source = nil
}

type Filesystem_Common_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Auth          string
	Source        *Filesystem_Common_Source
	MetaConfig    map[string]string
	StorageConfig map[string]string
	ClientConfig  map[string]string
}

func (b0 Filesystem_Common_builder) Build() *Filesystem_Common {
	m0 := &Filesystem_Common{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Auth = b.Auth
	x.xxx_hidden_Source = b.Source
	x.xxx_hidden_MetaConfig = b.MetaConfig
	x.xxx_hidden_StorageConfig = b.StorageConfig
	x.xxx_hidden_ClientConfig = b.ClientConfig
	return m0
}

type Filesystem_Common_Source struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type       SourceType             `protobuf:"varint,1,opt,name=type,proto3,enum=beegfs.SourceType" json:"type,omitempty"`
	xxx_hidden_Repo       string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	xxx_hidden_Management string                 `protobuf:"bytes,3,opt,name=management,proto3" json:"management,omitempty"`
	xxx_hidden_Meta       string                 `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	xxx_hidden_Storage    string                 `protobuf:"bytes,5,opt,name=storage,proto3" json:"storage,omitempty"`
	xxx_hidden_Remote     string                 `protobuf:"bytes,6,opt,name=remote,proto3" json:"remote,omitempty"`
	xxx_hidden_Sync       string                 `protobuf:"bytes,7,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Filesystem_Common_Source) Reset() {
	*x = Filesystem_Common_Source{}
	mi := &file_beegfs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filesystem_Common_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filesystem_Common_Source) ProtoMessage() {}

func (x *Filesystem_Common_Source) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Filesystem_Common_Source) GetType() SourceType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return SourceType_UNKNOWN
}

func (x *Filesystem_Common_Source) GetRepo() string {
	if x != nil {
		return x.xxx_hidden_Repo
	}
	return ""
}

func (x *Filesystem_Common_Source) GetManagement() string {
	if x != nil {
		return x.xxx_hidden_Management
	}
	return ""
}

func (x *Filesystem_Common_Source) GetMeta() string {
	if x != nil {
		return x.xxx_hidden_Meta
	}
	return ""
}

func (x *Filesystem_Common_Source) GetStorage() string {
	if x != nil {
		return x.xxx_hidden_Storage
	}
	return ""
}

func (x *Filesystem_Common_Source) GetRemote() string {
	if x != nil {
		return x.xxx_hidden_Remote
	}
	return ""
}

func (x *Filesystem_Common_Source) GetSync() string {
	if x != nil {
		return x.xxx_hidden_Sync
	}
	return ""
}

func (x *Filesystem_Common_Source) SetType(v SourceType) {
	x.xxx_hidden_Type = v
}

func (x *Filesystem_Common_Source) SetRepo(v string) {
	x.xxx_hidden_Repo = v
}

func (x *Filesystem_Common_Source) SetManagement(v string) {
	x.xxx_hidden_Management = v
}

func (x *Filesystem_Common_Source) SetMeta(v string) {
	x.xxx_hidden_Meta = v
}

func (x *Filesystem_Common_Source) SetStorage(v string) {
	x.xxx_hidden_Storage = v
}

func (x *Filesystem_Common_Source) SetRemote(v string) {
	x.xxx_hidden_Remote = v
}

func (x *Filesystem_Common_Source) SetSync(v string) {
	x.xxx_hidden_Sync = v
}

type Filesystem_Common_Source_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type       SourceType
	Repo       string
	Management string
	Meta       string
	Storage    string
	Remote     string
	Sync       string
}

func (b0 Filesystem_Common_Source_builder) Build() *Filesystem_Common_Source {
	m0 := &Filesystem_Common_Source{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Repo = b.Repo
	x.xxx_hidden_Management = b.Management
	x.xxx_hidden_Meta = b.Meta
	x.xxx_hidden_Storage = b.Storage
	x.xxx_hidden_Remote = b.Remote
	x.xxx_hidden_Sync = b.Sync
	return m0
}

type Node_Source struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type SourceType             `protobuf:"varint,1,opt,name=type,proto3,enum=beegfs.SourceType" json:"type,omitempty"`
	xxx_hidden_Ref  string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Node_Source) Reset() {
	*x = Node_Source{}
	mi := &file_beegfs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node_Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node_Source) ProtoMessage() {}

func (x *Node_Source) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Node_Source) GetType() SourceType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return SourceType_UNKNOWN
}

func (x *Node_Source) GetRef() string {
	if x != nil {
		return x.xxx_hidden_Ref
	}
	return ""
}

func (x *Node_Source) SetType(v SourceType) {
	x.xxx_hidden_Type = v
}

func (x *Node_Source) SetRef(v string) {
	x.xxx_hidden_Ref = v
}

type Node_Source_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type SourceType
	Ref  string
}

func (b0 Node_Source_builder) Build() *Node_Source {
	m0 := &Node_Source{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Ref = b.Ref
	return m0
}

type Target_UnderlyingFSOpts struct {
	state                  protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Device      string                         `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	xxx_hidden_Type        Target_UnderlyingFSOpts_FsType `protobuf:"varint,2,opt,name=type,proto3,enum=beegfs.Target_UnderlyingFSOpts_FsType" json:"type,omitempty"`
	xxx_hidden_FormatFlags string                         `protobuf:"bytes,3,opt,name=format_flags,json=formatFlags,proto3" json:"format_flags,omitempty"`
	xxx_hidden_MountFlags  string                         `protobuf:"bytes,4,opt,name=mount_flags,json=mountFlags,proto3" json:"mount_flags,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Target_UnderlyingFSOpts) Reset() {
	*x = Target_UnderlyingFSOpts{}
	mi := &file_beegfs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target_UnderlyingFSOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target_UnderlyingFSOpts) ProtoMessage() {}

func (x *Target_UnderlyingFSOpts) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Target_UnderlyingFSOpts) GetDevice() string {
	if x != nil {
		return x.xxx_hidden_Device
	}
	return ""
}

func (x *Target_UnderlyingFSOpts) GetType() Target_UnderlyingFSOpts_FsType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return Target_UnderlyingFSOpts_UNSPECIFIED
}

func (x *Target_UnderlyingFSOpts) GetFormatFlags() string {
	if x != nil {
		return x.xxx_hidden_FormatFlags
	}
	return ""
}

func (x *Target_UnderlyingFSOpts) GetMountFlags() string {
	if x != nil {
		return x.xxx_hidden_MountFlags
	}
	return ""
}

func (x *Target_UnderlyingFSOpts) SetDevice(v string) {
	x.xxx_hidden_Device = v
}

func (x *Target_UnderlyingFSOpts) SetType(v Target_UnderlyingFSOpts_FsType) {
	x.xxx_hidden_Type = v
}

func (x *Target_UnderlyingFSOpts) SetFormatFlags(v string) {
	x.xxx_hidden_FormatFlags = v
}

func (x *Target_UnderlyingFSOpts) SetMountFlags(v string) {
	x.xxx_hidden_MountFlags = v
}

type Target_UnderlyingFSOpts_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Device      string
	Type        Target_UnderlyingFSOpts_FsType
	FormatFlags string
	MountFlags  string
}

func (b0 Target_UnderlyingFSOpts_builder) Build() *Target_UnderlyingFSOpts {
	m0 := &Target_UnderlyingFSOpts{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Device = b.Device
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_FormatFlags = b.FormatFlags
	x.xxx_hidden_MountFlags = b.MountFlags
	return m0
}

var File_beegfs_proto protoreflect.FileDescriptor

var file_beegfs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x08, 0x4c, 0x65, 0x67, 0x61, 0x63,
	0x79, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x75, 0x6d, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x93, 0x01, 0x0a, 0x0b, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x53, 0x65, 0x74, 0x12, 0x15, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x03, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x19, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x01, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x09, 0x6c,
	0x65, 0x67, 0x61, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x49, 0x64,
	0x48, 0x02, 0x52, 0x08, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42,
	0x06, 0x0a, 0x04, 0x5f, 0x75, 0x69, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x5f, 0x69, 0x64, 0x22,
	0x74, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x73, 0x5f, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x73, 0x55, 0x75, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x65, 0x65, 0x67,
	0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x49, 0x0a, 0x13, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x66, 0x73, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66,
	0x73, 0x55, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x48, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x73, 0x5f, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x73, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x76, 0x0a, 0x13, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x73, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x66, 0x73, 0x55, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x60, 0x0a, 0x12, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x73, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x73, 0x55, 0x75, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x22, 0x76, 0x0a, 0x13, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x66,
	0x73, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x73,
	0x55, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xea, 0x01, 0x0a,
	0x0b, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x62, 0x65,
	0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x07, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22,
	0x58, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x49, 0x44, 0x4c,
	0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x50, 0x50, 0x4c, 0x59, 0x49, 0x4e, 0x47, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x03, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41,
	0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x05, 0x22, 0x8c, 0x07, 0x0a, 0x0a, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x33, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x31, 0x0a,
	0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x1a, 0x47, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0xcc, 0x05, 0x0a, 0x06, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x38, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66,
	0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x61, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x53,
	0x0a, 0x0e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x50, 0x0a, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x62, 0x65, 0x65,
	0x67, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0xbe, 0x01, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x12, 0x1e, 0x0a, 0x0a,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x79, 0x6e, 0x63, 0x1a, 0x3d, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x61, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x40, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3f, 0x0a, 0x11, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x58, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2b, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x65, 0x65, 0x67,
	0x66, 0x73, 0x2e, 0x4e, 0x69, 0x63, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x73, 0x22, 0x91, 0x03, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6e, 0x75, 0x6d,
	0x49, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x2b, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73,
	0x2e, 0x4e, 0x69, 0x63, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x12, 0x28, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x65, 0x65,
	0x67, 0x66, 0x73, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48,
	0x00, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x88, 0x01, 0x01, 0x1a, 0x39, 0x0a, 0x0b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x42, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x66,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x66, 0x42, 0x09, 0x0a, 0x07, 0x5f,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x2d, 0x0a, 0x03, 0x4e, 0x69, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0xcf, 0x02, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x6e, 0x75, 0x6d, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x5f,
	0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x6f, 0x6f, 0x74, 0x44,
	0x69, 0x72, 0x12, 0x38, 0x0a, 0x04, 0x75, 0x6c, 0x66, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x2e, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x79, 0x69, 0x6e, 0x67, 0x46, 0x53, 0x4f, 0x70, 0x74,
	0x73, 0x48, 0x00, 0x52, 0x04, 0x75, 0x6c, 0x66, 0x73, 0x88, 0x01, 0x01, 0x1a, 0xcf, 0x01, 0x0a,
	0x10, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x79, 0x69, 0x6e, 0x67, 0x46, 0x53, 0x4f, 0x70, 0x74,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73,
	0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x2e, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x79, 0x69,
	0x6e, 0x67, 0x46, 0x53, 0x4f, 0x70, 0x74, 0x73, 0x2e, 0x46, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x5f,
	0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x22, 0x23, 0x0a, 0x06, 0x46, 0x73, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x45, 0x58, 0x54, 0x34, 0x10, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x75, 0x6c, 0x66, 0x73, 0x2a, 0x5a, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x44, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x54, 0x41, 0x52, 0x47, 0x45, 0x54, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x55, 0x44, 0x44,
	0x59, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x4f,
	0x4c, 0x10, 0x04, 0x2a, 0x6e, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x19, 0x0a, 0x15, 0x4e, 0x4f, 0x44, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4c,
	0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x45, 0x54, 0x41, 0x10, 0x02,
	0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x03, 0x12, 0x0e, 0x0a,
	0x0a, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x59, 0x4e,
	0x43, 0x10, 0x06, 0x2a, 0x5e, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x63, 0x68, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x1e, 0x52, 0x45, 0x41, 0x43,
	0x48, 0x41, 0x42, 0x49, 0x4c, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x4f, 0x46, 0x46,
	0x4c, 0x49, 0x4e, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x46, 0x46, 0x4c, 0x49, 0x4e,
	0x45, 0x10, 0x03, 0x2a, 0x5a, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x63, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x1d, 0x43, 0x4f, 0x4e, 0x53, 0x49,
	0x53, 0x54, 0x45, 0x4e, 0x43, 0x59, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x4f,
	0x4f, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x45, 0x45, 0x44, 0x53, 0x5f, 0x52, 0x45,
	0x53, 0x59, 0x4e, 0x43, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x44, 0x10, 0x03, 0x2a,
	0x51, 0x0a, 0x0c, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x50, 0x6f, 0x6f, 0x6c, 0x12,
	0x1d, 0x0a, 0x19, 0x43, 0x41, 0x50, 0x41, 0x43, 0x49, 0x54, 0x59, 0x5f, 0x50, 0x4f, 0x4f, 0x4c,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x4e, 0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4c, 0x4f,
	0x57, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x4e, 0x43, 0x59,
	0x10, 0x03, 0x2a, 0x3b, 0x0a, 0x07, 0x4e, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a,
	0x14, 0x4e, 0x49, 0x43, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x54, 0x48, 0x45, 0x52,
	0x4e, 0x45, 0x54, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x44, 0x4d, 0x41, 0x10, 0x02, 0x2a,
	0x5d, 0x0a, 0x0b, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x49, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d,
	0x0a, 0x19, 0x51, 0x55, 0x4f, 0x54, 0x41, 0x5f, 0x49, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x16, 0x0a,
	0x12, 0x51, 0x55, 0x4f, 0x54, 0x41, 0x5f, 0x49, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55,
	0x53, 0x45, 0x52, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x51, 0x55, 0x4f, 0x54, 0x41, 0x5f, 0x49,
	0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x52, 0x4f, 0x55, 0x50, 0x10, 0x02, 0x2a, 0x53,
	0x0a, 0x09, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x51,
	0x55, 0x4f, 0x54, 0x41, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x51, 0x55, 0x4f, 0x54, 0x41,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x50, 0x41, 0x43, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a,
	0x10, 0x51, 0x55, 0x4f, 0x54, 0x41, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x49, 0x4e, 0x4f, 0x44,
	0x45, 0x10, 0x02, 0x2a, 0x31, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x43,
	0x4b, 0x41, 0x47, 0x45, 0x10, 0x02, 0x32, 0xd3, 0x01, 0x0a, 0x08, 0x42, 0x65, 0x65, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x12, 0x41, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e,
	0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x65, 0x65, 0x67,
	0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1a, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62,
	0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x06, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x12, 0x1a, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x43, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x29, 0x5a, 0x27,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x6e, 0x6b,
	0x70, 0x61, 0x72, 0x71, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f,
	0x2f, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_beegfs_proto_enumTypes = make([]protoimpl.EnumInfo, 11)
var file_beegfs_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_beegfs_proto_goTypes = []any{
	(EntityType)(0),                     // 0: beegfs.EntityType
	(NodeType)(0),                       // 1: beegfs.NodeType
	(ReachabilityState)(0),              // 2: beegfs.ReachabilityState
	(ConsistencyState)(0),               // 3: beegfs.ConsistencyState
	(CapacityPool)(0),                   // 4: beegfs.CapacityPool
	(NicType)(0),                        // 5: beegfs.NicType
	(QuotaIdType)(0),                    // 6: beegfs.QuotaIdType
	(QuotaType)(0),                      // 7: beegfs.QuotaType
	(SourceType)(0),                     // 8: beegfs.SourceType
	(AgentStatus_State)(0),              // 9: beegfs.AgentStatus.State
	(Target_UnderlyingFSOpts_FsType)(0), // 10: beegfs.Target.UnderlyingFSOpts.FsType
	(*LegacyId)(nil),                    // 11: beegfs.LegacyId
	(*EntityIdSet)(nil),                 // 12: beegfs.EntityIdSet
	(*AgentUpdateRequest)(nil),          // 13: beegfs.AgentUpdateRequest
	(*AgentUpdateResponse)(nil),         // 14: beegfs.AgentUpdateResponse
	(*AgentStatusRequest)(nil),          // 15: beegfs.AgentStatusRequest
	(*AgentStatusResponse)(nil),         // 16: beegfs.AgentStatusResponse
	(*AgentCancelRequest)(nil),          // 17: beegfs.AgentCancelRequest
	(*AgentCancelResponse)(nil),         // 18: beegfs.AgentCancelResponse
	(*AgentStatus)(nil),                 // 19: beegfs.AgentStatus
	(*Filesystem)(nil),                  // 20: beegfs.Filesystem
	(*Agent)(nil),                       // 21: beegfs.Agent
	(*Node)(nil),                        // 22: beegfs.Node
	(*Nic)(nil),                         // 23: beegfs.Nic
	(*Target)(nil),                      // 24: beegfs.Target
	nil,                                 // 25: beegfs.Filesystem.AgentEntry
	(*Filesystem_Common)(nil),           // 26: beegfs.Filesystem.Common
	(*Filesystem_Common_Source)(nil),    // 27: beegfs.Filesystem.Common.Source
	nil,                                 // 28: beegfs.Filesystem.Common.MetaConfigEntry
	nil,                                 // 29: beegfs.Filesystem.Common.StorageConfigEntry
	nil,                                 // 30: beegfs.Filesystem.Common.ClientConfigEntry
	nil,                                 // 31: beegfs.Node.ConfigEntry
	(*Node_Source)(nil),                 // 32: beegfs.Node.Source
	(*Target_UnderlyingFSOpts)(nil),     // 33: beegfs.Target.UnderlyingFSOpts
	(*timestamppb.Timestamp)(nil),       // 34: google.protobuf.Timestamp
}
var file_beegfs_proto_depIdxs = []int32{
	1,  // 0: beegfs.LegacyId.node_type:type_name -> beegfs.NodeType
	11, // 1: beegfs.EntityIdSet.legacy_id:type_name -> beegfs.LegacyId
	20, // 2: beegfs.AgentUpdateRequest.config:type_name -> beegfs.Filesystem
	19, // 3: beegfs.AgentStatusResponse.status:type_name -> beegfs.AgentStatus
	19, // 4: beegfs.AgentCancelResponse.status:type_name -> beegfs.AgentStatus
	9,  // 5: beegfs.AgentStatus.state:type_name -> beegfs.AgentStatus.State
	34, // 6: beegfs.AgentStatus.updated:type_name -> google.protobuf.Timestamp
	25, // 7: beegfs.Filesystem.agent:type_name -> beegfs.Filesystem.AgentEntry
	26, // 8: beegfs.Filesystem.common:type_name -> beegfs.Filesystem.Common
	22, // 9: beegfs.Agent.nodes:type_name -> beegfs.Node
	23, // 10: beegfs.Agent.interfaces:type_name -> beegfs.Nic
	1,  // 11: beegfs.Node.node_type:type_name -> beegfs.NodeType
	31, // 12: beegfs.Node.config:type_name -> beegfs.Node.ConfigEntry
	23, // 13: beegfs.Node.interfaces:type_name -> beegfs.Nic
	24, // 14: beegfs.Node.targets:type_name -> beegfs.Target
	32, // 15: beegfs.Node.source:type_name -> beegfs.Node.Source
	33, // 16: beegfs.Target.ulfs:type_name -> beegfs.Target.UnderlyingFSOpts
	21, // 17: beegfs.Filesystem.AgentEntry.value:type_name -> beegfs.Agent
	27, // 18: beegfs.Filesystem.Common.source:type_name -> beegfs.Filesystem.Common.Source
	28, // 19: beegfs.Filesystem.Common.meta_config:type_name -> beegfs.Filesystem.Common.MetaConfigEntry
	29, // 20: beegfs.Filesystem.Common.storage_config:type_name -> beegfs.Filesystem.Common.StorageConfigEntry
	30, // 21: beegfs.Filesystem.Common.client_config:type_name -> beegfs.Filesystem.Common.ClientConfigEntry
	8,  // 22: beegfs.Filesystem.Common.Source.type:type_name -> beegfs.SourceType
	8,  // 23: beegfs.Node.Source.type:type_name -> beegfs.SourceType
	10, // 24: beegfs.Target.UnderlyingFSOpts.type:type_name -> beegfs.Target.UnderlyingFSOpts.FsType
	13, // 25: beegfs.BeeAgent.Update:input_type -> beegfs.AgentUpdateRequest
	15, // 26: beegfs.BeeAgent.Status:input_type -> beegfs.AgentStatusRequest
	17, // 27: beegfs.BeeAgent.Cancel:input_type -> beegfs.AgentCancelRequest
	14, // 28: beegfs.BeeAgent.Update:output_type -> beegfs.AgentUpdateResponse
	16, // 29: beegfs.BeeAgent.Status:output_type -> beegfs.AgentStatusResponse
	18, // 30: beegfs.BeeAgent.Cancel:output_type -> beegfs.AgentCancelResponse
	28, // [28:31] is the sub-list for method output_type
	25, // [25:28] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_beegfs_proto_init() }
func file_beegfs_proto_init() {
	if File_beegfs_proto != nil {
		return
	}
	file_beegfs_proto_msgTypes[1].OneofWrappers = []any{}
	file_beegfs_proto_msgTypes[11].OneofWrappers = []any{}
	file_beegfs_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beegfs_proto_rawDesc,
			NumEnums:      11,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beegfs_proto_goTypes,
		DependencyIndexes: file_beegfs_proto_depIdxs,
		EnumInfos:         file_beegfs_proto_enumTypes,
		MessageInfos:      file_beegfs_proto_msgTypes,
	}.Build()
	File_beegfs_proto = out.File
	file_beegfs_proto_rawDesc = nil
	file_beegfs_proto_goTypes = nil
	file_beegfs_proto_depIdxs = nil
}
