// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: beegfs.proto

package beegfs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Nic_Type int32

const (
	Nic_ETHERNET Nic_Type = 0
	Nic_SDP      Nic_Type = 1
	Nic_RDMA     Nic_Type = 3
)

// Enum value maps for Nic_Type.
var (
	Nic_Type_name = map[int32]string{
		0: "ETHERNET",
		1: "SDP",
		3: "RDMA",
	}
	Nic_Type_value = map[string]int32{
		"ETHERNET": 0,
		"SDP":      1,
		"RDMA":     3,
	}
)

func (x Nic_Type) Enum() *Nic_Type {
	p := new(Nic_Type)
	*p = x
	return p
}

func (x Nic_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Nic_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[0].Descriptor()
}

func (Nic_Type) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[0]
}

func (x Nic_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Nic_Type.Descriptor instead.
func (Nic_Type) EnumDescriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{0, 0}
}

type GetNodeListResp_Node_Type int32

const (
	GetNodeListResp_Node_CLIENT  GetNodeListResp_Node_Type = 0
	GetNodeListResp_Node_META    GetNodeListResp_Node_Type = 1
	GetNodeListResp_Node_STORAGE GetNodeListResp_Node_Type = 2
)

// Enum value maps for GetNodeListResp_Node_Type.
var (
	GetNodeListResp_Node_Type_name = map[int32]string{
		0: "CLIENT",
		1: "META",
		2: "STORAGE",
	}
	GetNodeListResp_Node_Type_value = map[string]int32{
		"CLIENT":  0,
		"META":    1,
		"STORAGE": 2,
	}
)

func (x GetNodeListResp_Node_Type) Enum() *GetNodeListResp_Node_Type {
	p := new(GetNodeListResp_Node_Type)
	*p = x
	return p
}

func (x GetNodeListResp_Node_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetNodeListResp_Node_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_beegfs_proto_enumTypes[1].Descriptor()
}

func (GetNodeListResp_Node_Type) Type() protoreflect.EnumType {
	return &file_beegfs_proto_enumTypes[1]
}

func (x GetNodeListResp_Node_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetNodeListResp_Node_Type.Descriptor instead.
func (GetNodeListResp_Node_Type) EnumDescriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{2, 0, 0}
}

type Nic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Name string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type Nic_Type `protobuf:"varint,3,opt,name=type,proto3,enum=beegfs.Nic_Type" json:"type,omitempty"`
}

func (x *Nic) Reset() {
	*x = Nic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beegfs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Nic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nic) ProtoMessage() {}

func (x *Nic) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nic.ProtoReflect.Descriptor instead.
func (*Nic) Descriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{0}
}

func (x *Nic) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Nic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Nic) GetType() Nic_Type {
	if x != nil {
		return x.Type
	}
	return Nic_ETHERNET
}

type GetNodeListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncludeNics bool `protobuf:"varint,1,opt,name=include_nics,json=includeNics,proto3" json:"include_nics,omitempty"`
}

func (x *GetNodeListReq) Reset() {
	*x = GetNodeListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beegfs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListReq) ProtoMessage() {}

func (x *GetNodeListReq) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListReq.ProtoReflect.Descriptor instead.
func (*GetNodeListReq) Descriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeListReq) GetIncludeNics() bool {
	if x != nil {
		return x.IncludeNics
	}
	return false
}

type GetNodeListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*GetNodeListResp_Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *GetNodeListResp) Reset() {
	*x = GetNodeListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beegfs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListResp) ProtoMessage() {}

func (x *GetNodeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListResp.ProtoReflect.Descriptor instead.
func (*GetNodeListResp) Descriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{2}
}

func (x *GetNodeListResp) GetNodes() []*GetNodeListResp_Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetNodeInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Key:
	//
	//	*GetNodeInfoReq_Uid
	//	*GetNodeInfoReq_Alias
	Key isGetNodeInfoReq_Key `protobuf_oneof:"key"`
}

func (x *GetNodeInfoReq) Reset() {
	*x = GetNodeInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beegfs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoReq) ProtoMessage() {}

func (x *GetNodeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoReq.ProtoReflect.Descriptor instead.
func (*GetNodeInfoReq) Descriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{3}
}

func (m *GetNodeInfoReq) GetKey() isGetNodeInfoReq_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (x *GetNodeInfoReq) GetUid() int64 {
	if x, ok := x.GetKey().(*GetNodeInfoReq_Uid); ok {
		return x.Uid
	}
	return 0
}

func (x *GetNodeInfoReq) GetAlias() string {
	if x, ok := x.GetKey().(*GetNodeInfoReq_Alias); ok {
		return x.Alias
	}
	return ""
}

type isGetNodeInfoReq_Key interface {
	isGetNodeInfoReq_Key()
}

type GetNodeInfoReq_Uid struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3,oneof"`
}

type GetNodeInfoReq_Alias struct {
	Alias string `protobuf:"bytes,2,opt,name=alias,proto3,oneof"`
}

func (*GetNodeInfoReq_Uid) isGetNodeInfoReq_Key() {}

func (*GetNodeInfoReq_Alias) isGetNodeInfoReq_Key() {}

type GetNodeInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nics []*Nic `protobuf:"bytes,1,rep,name=nics,proto3" json:"nics,omitempty"`
}

func (x *GetNodeInfoResp) Reset() {
	*x = GetNodeInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beegfs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResp) ProtoMessage() {}

func (x *GetNodeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResp.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResp) Descriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeInfoResp) GetNics() []*Nic {
	if x != nil {
		return x.Nics
	}
	return nil
}

type GetNodeListResp_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        int64                     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NodeId     uint32                    `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Type       GetNodeListResp_Node_Type `protobuf:"varint,3,opt,name=type,proto3,enum=beegfs.GetNodeListResp_Node_Type" json:"type,omitempty"`
	Alias      string                    `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	BeemsgPort uint32                    `protobuf:"varint,5,opt,name=beemsg_port,json=beemsgPort,proto3" json:"beemsg_port,omitempty"`
	Nics       []*Nic                    `protobuf:"bytes,6,rep,name=nics,proto3" json:"nics,omitempty"`
}

func (x *GetNodeListResp_Node) Reset() {
	*x = GetNodeListResp_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_beegfs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNodeListResp_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeListResp_Node) ProtoMessage() {}

func (x *GetNodeListResp_Node) ProtoReflect() protoreflect.Message {
	mi := &file_beegfs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeListResp_Node.ProtoReflect.Descriptor instead.
func (*GetNodeListResp_Node) Descriptor() ([]byte, []int) {
	return file_beegfs_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetNodeListResp_Node) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetNodeListResp_Node) GetNodeId() uint32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *GetNodeListResp_Node) GetType() GetNodeListResp_Node_Type {
	if x != nil {
		return x.Type
	}
	return GetNodeListResp_Node_CLIENT
}

func (x *GetNodeListResp_Node) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *GetNodeListResp_Node) GetBeemsgPort() uint32 {
	if x != nil {
		return x.BeemsgPort
	}
	return 0
}

func (x *GetNodeListResp_Node) GetNics() []*Nic {
	if x != nil {
		return x.Nics
	}
	return nil
}

var File_beegfs_proto protoreflect.FileDescriptor

var file_beegfs_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x22, 0x7c, 0x0a, 0x03, 0x4e, 0x69, 0x63, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4e, 0x69, 0x63,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x27, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x45, 0x54, 0x48, 0x45, 0x52, 0x4e, 0x45, 0x54, 0x10,
	0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x44, 0x50, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x44,
	0x4d, 0x41, 0x10, 0x03, 0x22, 0x33, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64,
	0x65, 0x5f, 0x6e, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x4e, 0x69, 0x63, 0x73, 0x22, 0xb3, 0x02, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62,
	0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x1a, 0xeb, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x69,
	0x61, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x65, 0x65, 0x6d, 0x73, 0x67, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x65, 0x65, 0x6d, 0x73, 0x67, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4e, 0x69, 0x63, 0x52, 0x04,
	0x6e, 0x69, 0x63, 0x73, 0x22, 0x29, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x45, 0x54, 0x41,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x10, 0x02, 0x22,
	0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x42, 0x05, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x32, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x04, 0x6e, 0x69, 0x63, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x4e,
	0x69, 0x63, 0x52, 0x04, 0x6e, 0x69, 0x63, 0x73, 0x32, 0x8c, 0x01, 0x0a, 0x0a, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x62, 0x65, 0x65, 0x67, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x6e, 0x6b, 0x70, 0x61, 0x72, 0x71, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x2f, 0x62, 0x65, 0x65, 0x67,
	0x66, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_beegfs_proto_rawDescOnce sync.Once
	file_beegfs_proto_rawDescData = file_beegfs_proto_rawDesc
)

func file_beegfs_proto_rawDescGZIP() []byte {
	file_beegfs_proto_rawDescOnce.Do(func() {
		file_beegfs_proto_rawDescData = protoimpl.X.CompressGZIP(file_beegfs_proto_rawDescData)
	})
	return file_beegfs_proto_rawDescData
}

var file_beegfs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_beegfs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_beegfs_proto_goTypes = []interface{}{
	(Nic_Type)(0),                  // 0: beegfs.Nic.Type
	(GetNodeListResp_Node_Type)(0), // 1: beegfs.GetNodeListResp.Node.Type
	(*Nic)(nil),                    // 2: beegfs.Nic
	(*GetNodeListReq)(nil),         // 3: beegfs.GetNodeListReq
	(*GetNodeListResp)(nil),        // 4: beegfs.GetNodeListResp
	(*GetNodeInfoReq)(nil),         // 5: beegfs.GetNodeInfoReq
	(*GetNodeInfoResp)(nil),        // 6: beegfs.GetNodeInfoResp
	(*GetNodeListResp_Node)(nil),   // 7: beegfs.GetNodeListResp.Node
}
var file_beegfs_proto_depIdxs = []int32{
	0, // 0: beegfs.Nic.type:type_name -> beegfs.Nic.Type
	7, // 1: beegfs.GetNodeListResp.nodes:type_name -> beegfs.GetNodeListResp.Node
	2, // 2: beegfs.GetNodeInfoResp.nics:type_name -> beegfs.Nic
	1, // 3: beegfs.GetNodeListResp.Node.type:type_name -> beegfs.GetNodeListResp.Node.Type
	2, // 4: beegfs.GetNodeListResp.Node.nics:type_name -> beegfs.Nic
	3, // 5: beegfs.Management.GetNodeList:input_type -> beegfs.GetNodeListReq
	5, // 6: beegfs.Management.GetNodeInfo:input_type -> beegfs.GetNodeInfoReq
	4, // 7: beegfs.Management.GetNodeList:output_type -> beegfs.GetNodeListResp
	6, // 8: beegfs.Management.GetNodeInfo:output_type -> beegfs.GetNodeInfoResp
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_beegfs_proto_init() }
func file_beegfs_proto_init() {
	if File_beegfs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_beegfs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Nic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beegfs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beegfs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beegfs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beegfs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_beegfs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNodeListResp_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_beegfs_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*GetNodeInfoReq_Uid)(nil),
		(*GetNodeInfoReq_Alias)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_beegfs_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beegfs_proto_goTypes,
		DependencyIndexes: file_beegfs_proto_depIdxs,
		EnumInfos:         file_beegfs_proto_enumTypes,
		MessageInfos:      file_beegfs_proto_msgTypes,
	}.Build()
	File_beegfs_proto = out.File
	file_beegfs_proto_rawDesc = nil
	file_beegfs_proto_goTypes = nil
	file_beegfs_proto_depIdxs = nil
}
