// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: license.proto
// Protobuf C++ Version: 6.31.1

#include "license.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace license {

inline constexpr VerifyFeatureResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_{static_cast< ::license::VerifyResult >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR VerifyFeatureResult::VerifyFeatureResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(VerifyFeatureResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VerifyFeatureResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VerifyFeatureResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VerifyFeatureResultDefaultTypeInternal() {}
  union {
    VerifyFeatureResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VerifyFeatureResultDefaultTypeInternal _VerifyFeatureResult_default_instance_;

inline constexpr VerifyCertResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        serial_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        result_{static_cast< ::license::VerifyResult >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR VerifyCertResult::VerifyCertResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(VerifyCertResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct VerifyCertResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR VerifyCertResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~VerifyCertResultDefaultTypeInternal() {}
  union {
    VerifyCertResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 VerifyCertResultDefaultTypeInternal _VerifyCertResult_default_instance_;

inline constexpr CertData::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        dns_names_{},
        organization_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        organizational_unit_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        country_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        locality_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        common_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        subject_serial_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        valid_from_{nullptr},
        valid_until_{nullptr},
        parent_data_{nullptr},
        serial_{::int64_t{0}},
        type_{static_cast< ::license::CertType >(0)},
        is_ca_{false} {}

template <typename>
PROTOBUF_CONSTEXPR CertData::CertData(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CertData_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CertDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CertDataDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CertDataDefaultTypeInternal() {}
  union {
    CertData _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CertDataDefaultTypeInternal _CertData_default_instance_;

inline constexpr GetCertDataResult::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_{nullptr},
        result_{static_cast< ::license::VerifyResult >(0)} {}

template <typename>
PROTOBUF_CONSTEXPR GetCertDataResult::GetCertDataResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(GetCertDataResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetCertDataResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetCertDataResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetCertDataResultDefaultTypeInternal() {}
  union {
    GetCertDataResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetCertDataResultDefaultTypeInternal _GetCertDataResult_default_instance_;
}  // namespace license
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_license_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_license_2eproto = nullptr;
const ::uint32_t
    TableStruct_license_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::license::VerifyCertResult, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::license::VerifyCertResult, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::license::VerifyCertResult, _impl_.serial_),
        PROTOBUF_FIELD_OFFSET(::license::VerifyCertResult, _impl_.message_),
        2,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::license::VerifyFeatureResult, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::license::VerifyFeatureResult, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::license::VerifyFeatureResult, _impl_.message_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::license::GetCertDataResult, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::license::GetCertDataResult, _impl_.result_),
        PROTOBUF_FIELD_OFFSET(::license::GetCertDataResult, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::license::GetCertDataResult, _impl_.message_),
        2,
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_._has_bits_),
        16, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.serial_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.organization_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.organizational_unit_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.country_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.locality_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.common_name_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.subject_serial_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.valid_from_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.valid_until_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.dns_names_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.is_ca_),
        PROTOBUF_FIELD_OFFSET(::license::CertData, _impl_.parent_data_),
        10,
        9,
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        ~0u,
        11,
        8,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::license::VerifyCertResult)},
        {9, sizeof(::license::VerifyFeatureResult)},
        {16, sizeof(::license::GetCertDataResult)},
        {25, sizeof(::license::CertData)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::license::_VerifyCertResult_default_instance_._instance,
    &::license::_VerifyFeatureResult_default_instance_._instance,
    &::license::_GetCertDataResult_default_instance_._instance,
    &::license::_CertData_default_instance_._instance,
};
const char descriptor_table_protodef_license_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rlicense.proto\022\007license\032\037google/protobu"
    "f/timestamp.proto\"Z\n\020VerifyCertResult\022%\n"
    "\006result\030\001 \001(\0162\025.license.VerifyResult\022\016\n\006"
    "serial\030\002 \001(\t\022\017\n\007message\030\003 \001(\t\"M\n\023VerifyF"
    "eatureResult\022%\n\006result\030\001 \001(\0162\025.license.V"
    "erifyResult\022\017\n\007message\030\002 \001(\t\"l\n\021GetCertD"
    "ataResult\022%\n\006result\030\001 \001(\0162\025.license.Veri"
    "fyResult\022\037\n\004data\030\002 \001(\0132\021.license.CertDat"
    "a\022\017\n\007message\030\003 \001(\t\"\210\003\n\010CertData\022\037\n\004type\030"
    "\001 \001(\0162\021.license.CertType\022\016\n\006serial\030\002 \001(\003"
    "\022\024\n\014organization\030\003 \001(\t\022\033\n\023organizational"
    "_unit\030\004 \001(\t\022\017\n\007country\030\005 \001(\t\022\020\n\010locality"
    "\030\006 \001(\t\022\023\n\013common_name\030\007 \001(\t\022\026\n\016subject_s"
    "erial\030\010 \001(\t\022.\n\nvalid_from\030\t \001(\0132\032.google"
    ".protobuf.Timestamp\022/\n\013valid_until\030\n \001(\013"
    "2\032.google.protobuf.Timestamp\022\033\n\tdns_name"
    "s\030\013 \003(\tR\010DNSNames\022\r\n\005is_ca\030\014 \001(\010\022+\n\013pare"
    "nt_data\030\r \001(\0132\021.license.CertDataH\000\210\001\001B\016\n"
    "\014_parent_data*^\n\014VerifyResult\022\026\n\022VERIFY_"
    "UNSPECIFIED\020\000\022\020\n\014VERIFY_ERROR\020\001\022\020\n\014VERIF"
    "Y_VALID\020\002\022\022\n\016VERIFY_INVALID\020\003*\274\001\n\010CertTy"
    "pe\022\031\n\025CERT_TYPE_UNSPECIFIED\020\000\022\025\n\021CERT_TY"
    "PE_CA_ROOT\020\001\022\035\n\031CERT_TYPE_CA_INTERMEDIAT"
    "E\020\002\022\025\n\021CERT_TYPE_PARTNER\020\003\022\026\n\022CERT_TYPE_"
    "CUSTOMER\020\004\022\027\n\023CERT_TYPE_TEMPORARY\020\005\022\027\n\023C"
    "ERT_TYPE_COMMUNITY\020\006B*Z(github.com/think"
    "parq/protobuf/go/licenseb\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_license_2eproto_deps[1] = {
        &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::absl::once_flag descriptor_table_license_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_license_2eproto = {
    false,
    false,
    1072,
    descriptor_table_protodef_license_2eproto,
    "license.proto",
    &descriptor_table_license_2eproto_once,
    descriptor_table_license_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_license_2eproto::offsets,
    file_level_enum_descriptors_license_2eproto,
    file_level_service_descriptors_license_2eproto,
};
namespace license {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL VerifyResult_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_license_2eproto);
  return file_level_enum_descriptors_license_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t VerifyResult_internal_data_[] = {
    262144u, 0u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CertType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_license_2eproto);
  return file_level_enum_descriptors_license_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t CertType_internal_data_[] = {
    458752u, 0u, };
// ===================================================================

class VerifyCertResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<VerifyCertResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_._has_bits_);
};

VerifyCertResult::VerifyCertResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyCertResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:license.VerifyCertResult)
}
PROTOBUF_NDEBUG_INLINE VerifyCertResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::license::VerifyCertResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        serial_(arena, from.serial_),
        message_(arena, from.message_) {}

VerifyCertResult::VerifyCertResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VerifyCertResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyCertResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VerifyCertResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:license.VerifyCertResult)
}
PROTOBUF_NDEBUG_INLINE VerifyCertResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        serial_(arena),
        message_(arena) {}

inline void VerifyCertResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
VerifyCertResult::~VerifyCertResult() {
  // @@protoc_insertion_point(destructor:license.VerifyCertResult)
  SharedDtor(*this);
}
inline void VerifyCertResult::SharedDtor(MessageLite& self) {
  VerifyCertResult& this_ = static_cast<VerifyCertResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.serial_.Destroy();
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL VerifyCertResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VerifyCertResult(arena);
}
constexpr auto VerifyCertResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VerifyCertResult),
                                            alignof(VerifyCertResult));
}
constexpr auto VerifyCertResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VerifyCertResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &VerifyCertResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VerifyCertResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VerifyCertResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<VerifyCertResult>(), &VerifyCertResult::ByteSizeLong,
              &VerifyCertResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_._cached_size_),
          false,
      },
      &VerifyCertResult::kDescriptorMethods,
      &descriptor_table_license_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VerifyCertResult_class_data_ =
        VerifyCertResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VerifyCertResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VerifyCertResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VerifyCertResult_class_data_.tc_table);
  return VerifyCertResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 46, 2>
VerifyCertResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    VerifyCertResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::license::VerifyCertResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .license.VerifyResult result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VerifyCertResult, _impl_.result_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_.result_)}},
    // string serial = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_.serial_)}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .license.VerifyResult result = 1;
    {PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_.result_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string serial = 2;
    {PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_.serial_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(VerifyCertResult, _impl_.message_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\30\0\6\7\0\0\0\0"
    "license.VerifyCertResult"
    "serial"
    "message"
  }},
};
PROTOBUF_NOINLINE void VerifyCertResult::Clear() {
// @@protoc_insertion_point(message_clear_start:license.VerifyCertResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.serial_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.result_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VerifyCertResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VerifyCertResult& this_ = static_cast<const VerifyCertResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VerifyCertResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VerifyCertResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:license.VerifyCertResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .license.VerifyResult result = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_result() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_result(), target);
    }
  }

  // string serial = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_serial().empty()) {
      const ::std::string& _s = this_._internal_serial();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.VerifyCertResult.serial");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string message = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.VerifyCertResult.message");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:license.VerifyCertResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VerifyCertResult::ByteSizeLong(const MessageLite& base) {
  const VerifyCertResult& this_ = static_cast<const VerifyCertResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VerifyCertResult::ByteSizeLong() const {
  const VerifyCertResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:license.VerifyCertResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string serial = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_serial().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_serial());
      }
    }
    // string message = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // .license.VerifyResult result = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_result() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_result());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VerifyCertResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VerifyCertResult*>(&to_msg);
  auto& from = static_cast<const VerifyCertResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:license.VerifyCertResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_serial().empty()) {
        _this->_internal_set_serial(from._internal_serial());
      } else {
        if (_this->_impl_.serial_.IsDefault()) {
          _this->_internal_set_serial("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_result() != 0) {
        _this->_impl_.result_ = from._impl_.result_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VerifyCertResult::CopyFrom(const VerifyCertResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:license.VerifyCertResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VerifyCertResult::InternalSwap(VerifyCertResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.serial_, &other->_impl_.serial_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata VerifyCertResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class VerifyFeatureResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<VerifyFeatureResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(VerifyFeatureResult, _impl_._has_bits_);
};

VerifyFeatureResult::VerifyFeatureResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyFeatureResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:license.VerifyFeatureResult)
}
PROTOBUF_NDEBUG_INLINE VerifyFeatureResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::license::VerifyFeatureResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

VerifyFeatureResult::VerifyFeatureResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const VerifyFeatureResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, VerifyFeatureResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  VerifyFeatureResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:license.VerifyFeatureResult)
}
PROTOBUF_NDEBUG_INLINE VerifyFeatureResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        message_(arena) {}

inline void VerifyFeatureResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
VerifyFeatureResult::~VerifyFeatureResult() {
  // @@protoc_insertion_point(destructor:license.VerifyFeatureResult)
  SharedDtor(*this);
}
inline void VerifyFeatureResult::SharedDtor(MessageLite& self) {
  VerifyFeatureResult& this_ = static_cast<VerifyFeatureResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL VerifyFeatureResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) VerifyFeatureResult(arena);
}
constexpr auto VerifyFeatureResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(VerifyFeatureResult),
                                            alignof(VerifyFeatureResult));
}
constexpr auto VerifyFeatureResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_VerifyFeatureResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &VerifyFeatureResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<VerifyFeatureResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &VerifyFeatureResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<VerifyFeatureResult>(), &VerifyFeatureResult::ByteSizeLong,
              &VerifyFeatureResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(VerifyFeatureResult, _impl_._cached_size_),
          false,
      },
      &VerifyFeatureResult::kDescriptorMethods,
      &descriptor_table_license_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull VerifyFeatureResult_class_data_ =
        VerifyFeatureResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
VerifyFeatureResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&VerifyFeatureResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(VerifyFeatureResult_class_data_.tc_table);
  return VerifyFeatureResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 43, 2>
VerifyFeatureResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(VerifyFeatureResult, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    VerifyFeatureResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::license::VerifyFeatureResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string message = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(VerifyFeatureResult, _impl_.message_)}},
    // .license.VerifyResult result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(VerifyFeatureResult, _impl_.result_), 1>(),
     {8, 1, 0, PROTOBUF_FIELD_OFFSET(VerifyFeatureResult, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .license.VerifyResult result = 1;
    {PROTOBUF_FIELD_OFFSET(VerifyFeatureResult, _impl_.result_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string message = 2;
    {PROTOBUF_FIELD_OFFSET(VerifyFeatureResult, _impl_.message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\33\0\7\0\0\0\0\0"
    "license.VerifyFeatureResult"
    "message"
  }},
};
PROTOBUF_NOINLINE void VerifyFeatureResult::Clear() {
// @@protoc_insertion_point(message_clear_start:license.VerifyFeatureResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_.result_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL VerifyFeatureResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const VerifyFeatureResult& this_ = static_cast<const VerifyFeatureResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL VerifyFeatureResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const VerifyFeatureResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:license.VerifyFeatureResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .license.VerifyResult result = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (this_._internal_result() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_result(), target);
    }
  }

  // string message = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.VerifyFeatureResult.message");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:license.VerifyFeatureResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t VerifyFeatureResult::ByteSizeLong(const MessageLite& base) {
  const VerifyFeatureResult& this_ = static_cast<const VerifyFeatureResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t VerifyFeatureResult::ByteSizeLong() const {
  const VerifyFeatureResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:license.VerifyFeatureResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // string message = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // .license.VerifyResult result = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (this_._internal_result() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_result());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void VerifyFeatureResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<VerifyFeatureResult*>(&to_msg);
  auto& from = static_cast<const VerifyFeatureResult&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:license.VerifyFeatureResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (from._internal_result() != 0) {
        _this->_impl_.result_ = from._impl_.result_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void VerifyFeatureResult::CopyFrom(const VerifyFeatureResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:license.VerifyFeatureResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void VerifyFeatureResult::InternalSwap(VerifyFeatureResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata VerifyFeatureResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetCertDataResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<GetCertDataResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_._has_bits_);
};

GetCertDataResult::GetCertDataResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetCertDataResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:license.GetCertDataResult)
}
PROTOBUF_NDEBUG_INLINE GetCertDataResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::license::GetCertDataResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_(arena, from.message_) {}

GetCertDataResult::GetCertDataResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const GetCertDataResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, GetCertDataResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetCertDataResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.data_ = ((cached_has_bits & 0x00000002u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.data_)
                : nullptr;
  _impl_.result_ = from._impl_.result_;

  // @@protoc_insertion_point(copy_constructor:license.GetCertDataResult)
}
PROTOBUF_NDEBUG_INLINE GetCertDataResult::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        message_(arena) {}

inline void GetCertDataResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, data_),
           0,
           offsetof(Impl_, result_) -
               offsetof(Impl_, data_) +
               sizeof(Impl_::result_));
}
GetCertDataResult::~GetCertDataResult() {
  // @@protoc_insertion_point(destructor:license.GetCertDataResult)
  SharedDtor(*this);
}
inline void GetCertDataResult::SharedDtor(MessageLite& self) {
  GetCertDataResult& this_ = static_cast<GetCertDataResult&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  delete this_._impl_.data_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL GetCertDataResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) GetCertDataResult(arena);
}
constexpr auto GetCertDataResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GetCertDataResult),
                                            alignof(GetCertDataResult));
}
constexpr auto GetCertDataResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_GetCertDataResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &GetCertDataResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<GetCertDataResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &GetCertDataResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<GetCertDataResult>(), &GetCertDataResult::ByteSizeLong,
              &GetCertDataResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_._cached_size_),
          false,
      },
      &GetCertDataResult::kDescriptorMethods,
      &descriptor_table_license_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull GetCertDataResult_class_data_ =
        GetCertDataResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
GetCertDataResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&GetCertDataResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(GetCertDataResult_class_data_.tc_table);
  return GetCertDataResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 41, 2>
GetCertDataResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    GetCertDataResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::license::GetCertDataResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .license.VerifyResult result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GetCertDataResult, _impl_.result_), 2>(),
     {8, 2, 0, PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.result_)}},
    // .license.CertData data = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.data_)}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .license.VerifyResult result = 1;
    {PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.result_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // .license.CertData data = 2;
    {PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.data_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.message_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::license::CertData>()},
  }},
  {{
    "\31\0\0\7\0\0\0\0"
    "license.GetCertDataResult"
    "message"
  }},
};
PROTOBUF_NOINLINE void GetCertDataResult::Clear() {
// @@protoc_insertion_point(message_clear_start:license.GetCertDataResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(_impl_.data_ != nullptr);
      _impl_.data_->Clear();
    }
  }
  _impl_.result_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL GetCertDataResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const GetCertDataResult& this_ = static_cast<const GetCertDataResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL GetCertDataResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const GetCertDataResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:license.GetCertDataResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .license.VerifyResult result = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (this_._internal_result() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_result(), target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .license.CertData data = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.data_, this_._impl_.data_->GetCachedSize(), target,
        stream);
  }

  // string message = 3;
  if ((cached_has_bits & 0x00000001u) != 0) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.GetCertDataResult.message");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:license.GetCertDataResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t GetCertDataResult::ByteSizeLong(const MessageLite& base) {
  const GetCertDataResult& this_ = static_cast<const GetCertDataResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t GetCertDataResult::ByteSizeLong() const {
  const GetCertDataResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:license.GetCertDataResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    // string message = 3;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // .license.CertData data = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.data_);
    }
    // .license.VerifyResult result = 1;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (this_._internal_result() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_result());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void GetCertDataResult::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetCertDataResult*>(&to_msg);
  auto& from = static_cast<const GetCertDataResult&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:license.GetCertDataResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000007u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      ABSL_DCHECK(from._impl_.data_ != nullptr);
      if (_this->_impl_.data_ == nullptr) {
        _this->_impl_.data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.data_);
      } else {
        _this->_impl_.data_->MergeFrom(*from._impl_.data_);
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (from._internal_result() != 0) {
        _this->_impl_.result_ = from._impl_.result_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetCertDataResult::CopyFrom(const GetCertDataResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:license.GetCertDataResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetCertDataResult::InternalSwap(GetCertDataResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.result_)
      + sizeof(GetCertDataResult::_impl_.result_)
      - PROTOBUF_FIELD_OFFSET(GetCertDataResult, _impl_.data_)>(
          reinterpret_cast<char*>(&_impl_.data_),
          reinterpret_cast<char*>(&other->_impl_.data_));
}

::google::protobuf::Metadata GetCertDataResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CertData::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CertData>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CertData, _impl_._has_bits_);
};

void CertData::clear_valid_from() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.valid_from_ != nullptr) _impl_.valid_from_->Clear();
  _impl_._has_bits_[0] &= ~0x00000040u;
}
void CertData::clear_valid_until() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.valid_until_ != nullptr) _impl_.valid_until_->Clear();
  _impl_._has_bits_[0] &= ~0x00000080u;
}
CertData::CertData(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CertData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:license.CertData)
}
PROTOBUF_NDEBUG_INLINE CertData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::license::CertData& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        dns_names_{visibility, arena, from.dns_names_},
        organization_(arena, from.organization_),
        organizational_unit_(arena, from.organizational_unit_),
        country_(arena, from.country_),
        locality_(arena, from.locality_),
        common_name_(arena, from.common_name_),
        subject_serial_(arena, from.subject_serial_) {}

CertData::CertData(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CertData& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CertData_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CertData* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.valid_from_ = ((cached_has_bits & 0x00000040u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.valid_from_)
                : nullptr;
  _impl_.valid_until_ = ((cached_has_bits & 0x00000080u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.valid_until_)
                : nullptr;
  _impl_.parent_data_ = ((cached_has_bits & 0x00000100u) != 0)
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.parent_data_)
                : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, serial_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, serial_),
           offsetof(Impl_, is_ca_) -
               offsetof(Impl_, serial_) +
               sizeof(Impl_::is_ca_));

  // @@protoc_insertion_point(copy_constructor:license.CertData)
}
PROTOBUF_NDEBUG_INLINE CertData::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        dns_names_{visibility, arena},
        organization_(arena),
        organizational_unit_(arena),
        country_(arena),
        locality_(arena),
        common_name_(arena),
        subject_serial_(arena) {}

inline void CertData::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, valid_from_),
           0,
           offsetof(Impl_, is_ca_) -
               offsetof(Impl_, valid_from_) +
               sizeof(Impl_::is_ca_));
}
CertData::~CertData() {
  // @@protoc_insertion_point(destructor:license.CertData)
  SharedDtor(*this);
}
inline void CertData::SharedDtor(MessageLite& self) {
  CertData& this_ = static_cast<CertData&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.organization_.Destroy();
  this_._impl_.organizational_unit_.Destroy();
  this_._impl_.country_.Destroy();
  this_._impl_.locality_.Destroy();
  this_._impl_.common_name_.Destroy();
  this_._impl_.subject_serial_.Destroy();
  delete this_._impl_.valid_from_;
  delete this_._impl_.valid_until_;
  delete this_._impl_.parent_data_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CertData::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CertData(arena);
}
constexpr auto CertData::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CertData, _impl_.dns_names_) +
          decltype(CertData::_impl_.dns_names_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(CertData), alignof(CertData), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CertData::PlacementNew_,
                                 sizeof(CertData),
                                 alignof(CertData));
  }
}
constexpr auto CertData::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CertData_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CertData::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CertData>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CertData::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CertData>(), &CertData::ByteSizeLong,
              &CertData::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CertData, _impl_._cached_size_),
          false,
      },
      &CertData::kDescriptorMethods,
      &descriptor_table_license_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CertData_class_data_ =
        CertData::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CertData::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CertData_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CertData_class_data_.tc_table);
  return CertData_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 13, 3, 113, 2>
CertData::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CertData, _impl_._has_bits_),
    0, // no _extensions_
    13, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294959104,  // skipmap
    offsetof(decltype(_table_), field_entries),
    13,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CertData_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::license::CertData>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .license.CertType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CertData, _impl_.type_), 10>(),
     {8, 10, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.type_)}},
    // int64 serial = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CertData, _impl_.serial_), 9>(),
     {16, 9, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.serial_)}},
    // string organization = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.organization_)}},
    // string organizational_unit = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.organizational_unit_)}},
    // string country = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 2, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.country_)}},
    // string locality = 6;
    {::_pbi::TcParser::FastUS1,
     {50, 3, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.locality_)}},
    // string common_name = 7;
    {::_pbi::TcParser::FastUS1,
     {58, 4, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.common_name_)}},
    // string subject_serial = 8;
    {::_pbi::TcParser::FastUS1,
     {66, 5, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.subject_serial_)}},
    // .google.protobuf.Timestamp valid_from = 9;
    {::_pbi::TcParser::FastMtS1,
     {74, 6, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.valid_from_)}},
    // .google.protobuf.Timestamp valid_until = 10;
    {::_pbi::TcParser::FastMtS1,
     {82, 7, 1, PROTOBUF_FIELD_OFFSET(CertData, _impl_.valid_until_)}},
    // repeated string dns_names = 11 [json_name = "DNSNames"];
    {::_pbi::TcParser::FastUR1,
     {90, 63, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.dns_names_)}},
    // bool is_ca = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CertData, _impl_.is_ca_), 11>(),
     {96, 11, 0, PROTOBUF_FIELD_OFFSET(CertData, _impl_.is_ca_)}},
    // optional .license.CertData parent_data = 13;
    {::_pbi::TcParser::FastMtS1,
     {106, 8, 2, PROTOBUF_FIELD_OFFSET(CertData, _impl_.parent_data_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .license.CertType type = 1;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.type_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int64 serial = 2;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.serial_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
    // string organization = 3;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.organization_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string organizational_unit = 4;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.organizational_unit_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string country = 5;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.country_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string locality = 6;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.locality_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string common_name = 7;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.common_name_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string subject_serial = 8;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.subject_serial_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .google.protobuf.Timestamp valid_from = 9;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.valid_from_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .google.protobuf.Timestamp valid_until = 10;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.valid_until_), _Internal::kHasBitsOffset + 7, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated string dns_names = 11 [json_name = "DNSNames"];
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.dns_names_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
    // bool is_ca = 12;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.is_ca_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional .license.CertData parent_data = 13;
    {PROTOBUF_FIELD_OFFSET(CertData, _impl_.parent_data_), _Internal::kHasBitsOffset + 8, 2,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::google::protobuf::Timestamp>()},
      {::_pbi::TcParser::GetTable<::license::CertData>()},
  }},
  {{
    "\20\0\0\14\23\7\10\13\16\0\0\11\0\0\0\0"
    "license.CertData"
    "organization"
    "organizational_unit"
    "country"
    "locality"
    "common_name"
    "subject_serial"
    "dns_names"
  }},
};
PROTOBUF_NOINLINE void CertData::Clear() {
// @@protoc_insertion_point(message_clear_start:license.CertData)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dns_names_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.organization_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.organizational_unit_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.country_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _impl_.locality_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _impl_.common_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      _impl_.subject_serial_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      ABSL_DCHECK(_impl_.valid_from_ != nullptr);
      _impl_.valid_from_->Clear();
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      ABSL_DCHECK(_impl_.valid_until_ != nullptr);
      _impl_.valid_until_->Clear();
    }
  }
  if ((cached_has_bits & 0x00000100u) != 0) {
    ABSL_DCHECK(_impl_.parent_data_ != nullptr);
    _impl_.parent_data_->Clear();
  }
  if ((cached_has_bits & 0x00000e00u) != 0) {
    ::memset(&_impl_.serial_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.is_ca_) -
        reinterpret_cast<char*>(&_impl_.serial_)) + sizeof(_impl_.is_ca_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CertData::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CertData& this_ = static_cast<const CertData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CertData::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CertData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:license.CertData)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .license.CertType type = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000400u) != 0) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_type(), target);
    }
  }

  // int64 serial = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000200u) != 0) {
    if (this_._internal_serial() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<2>(
              stream, this_._internal_serial(), target);
    }
  }

  // string organization = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_organization().empty()) {
      const ::std::string& _s = this_._internal_organization();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.CertData.organization");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string organizational_unit = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_organizational_unit().empty()) {
      const ::std::string& _s = this_._internal_organizational_unit();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.CertData.organizational_unit");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // string country = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_country().empty()) {
      const ::std::string& _s = this_._internal_country();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.CertData.country");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // string locality = 6;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (!this_._internal_locality().empty()) {
      const ::std::string& _s = this_._internal_locality();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.CertData.locality");
      target = stream->WriteStringMaybeAliased(6, _s, target);
    }
  }

  // string common_name = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (!this_._internal_common_name().empty()) {
      const ::std::string& _s = this_._internal_common_name();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.CertData.common_name");
      target = stream->WriteStringMaybeAliased(7, _s, target);
    }
  }

  // string subject_serial = 8;
  if ((this_._impl_._has_bits_[0] & 0x00000020u) != 0) {
    if (!this_._internal_subject_serial().empty()) {
      const ::std::string& _s = this_._internal_subject_serial();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.CertData.subject_serial");
      target = stream->WriteStringMaybeAliased(8, _s, target);
    }
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // .google.protobuf.Timestamp valid_from = 9;
  if ((cached_has_bits & 0x00000040u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        9, *this_._impl_.valid_from_, this_._impl_.valid_from_->GetCachedSize(), target,
        stream);
  }

  // .google.protobuf.Timestamp valid_until = 10;
  if ((cached_has_bits & 0x00000080u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        10, *this_._impl_.valid_until_, this_._impl_.valid_until_->GetCachedSize(), target,
        stream);
  }

  // repeated string dns_names = 11 [json_name = "DNSNames"];
  for (int i = 0, n = this_._internal_dns_names_size(); i < n; ++i) {
    const auto& s = this_._internal_dns_names().Get(i);
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "license.CertData.dns_names");
    target = stream->WriteString(11, s, target);
  }

  // bool is_ca = 12;
  if ((cached_has_bits & 0x00000800u) != 0) {
    if (this_._internal_is_ca() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          12, this_._internal_is_ca(), target);
    }
  }

  // optional .license.CertData parent_data = 13;
  if ((cached_has_bits & 0x00000100u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        13, *this_._impl_.parent_data_, this_._impl_.parent_data_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:license.CertData)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CertData::ByteSizeLong(const MessageLite& base) {
  const CertData& this_ = static_cast<const CertData&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CertData::ByteSizeLong() const {
  const CertData& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:license.CertData)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated string dns_names = 11 [json_name = "DNSNames"];
    {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_dns_names().size());
      for (int i = 0, n = this_._internal_dns_names().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_dns_names().Get(i));
      }
    }
  }
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    // string organization = 3;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_organization().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_organization());
      }
    }
    // string organizational_unit = 4;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_organizational_unit().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_organizational_unit());
      }
    }
    // string country = 5;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_country().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_country());
      }
    }
    // string locality = 6;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (!this_._internal_locality().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_locality());
      }
    }
    // string common_name = 7;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (!this_._internal_common_name().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_common_name());
      }
    }
    // string subject_serial = 8;
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (!this_._internal_subject_serial().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_subject_serial());
      }
    }
    // .google.protobuf.Timestamp valid_from = 9;
    if ((cached_has_bits & 0x00000040u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.valid_from_);
    }
    // .google.protobuf.Timestamp valid_until = 10;
    if ((cached_has_bits & 0x00000080u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.valid_until_);
    }
  }
  if ((cached_has_bits & 0x00000f00u) != 0) {
    // optional .license.CertData parent_data = 13;
    if ((cached_has_bits & 0x00000100u) != 0) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.parent_data_);
    }
    // int64 serial = 2;
    if ((cached_has_bits & 0x00000200u) != 0) {
      if (this_._internal_serial() != 0) {
        total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
            this_._internal_serial());
      }
    }
    // .license.CertType type = 1;
    if ((cached_has_bits & 0x00000400u) != 0) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
    // bool is_ca = 12;
    if ((cached_has_bits & 0x00000800u) != 0) {
      if (this_._internal_is_ca() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CertData::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CertData*>(&to_msg);
  auto& from = static_cast<const CertData&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:license.CertData)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_dns_names()->MergeFrom(from._internal_dns_names());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_organization().empty()) {
        _this->_internal_set_organization(from._internal_organization());
      } else {
        if (_this->_impl_.organization_.IsDefault()) {
          _this->_internal_set_organization("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_organizational_unit().empty()) {
        _this->_internal_set_organizational_unit(from._internal_organizational_unit());
      } else {
        if (_this->_impl_.organizational_unit_.IsDefault()) {
          _this->_internal_set_organizational_unit("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_country().empty()) {
        _this->_internal_set_country(from._internal_country());
      } else {
        if (_this->_impl_.country_.IsDefault()) {
          _this->_internal_set_country("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (!from._internal_locality().empty()) {
        _this->_internal_set_locality(from._internal_locality());
      } else {
        if (_this->_impl_.locality_.IsDefault()) {
          _this->_internal_set_locality("");
        }
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (!from._internal_common_name().empty()) {
        _this->_internal_set_common_name(from._internal_common_name());
      } else {
        if (_this->_impl_.common_name_.IsDefault()) {
          _this->_internal_set_common_name("");
        }
      }
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (!from._internal_subject_serial().empty()) {
        _this->_internal_set_subject_serial(from._internal_subject_serial());
      } else {
        if (_this->_impl_.subject_serial_.IsDefault()) {
          _this->_internal_set_subject_serial("");
        }
      }
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      ABSL_DCHECK(from._impl_.valid_from_ != nullptr);
      if (_this->_impl_.valid_from_ == nullptr) {
        _this->_impl_.valid_from_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.valid_from_);
      } else {
        _this->_impl_.valid_from_->MergeFrom(*from._impl_.valid_from_);
      }
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      ABSL_DCHECK(from._impl_.valid_until_ != nullptr);
      if (_this->_impl_.valid_until_ == nullptr) {
        _this->_impl_.valid_until_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.valid_until_);
      } else {
        _this->_impl_.valid_until_->MergeFrom(*from._impl_.valid_until_);
      }
    }
  }
  if ((cached_has_bits & 0x00000f00u) != 0) {
    if ((cached_has_bits & 0x00000100u) != 0) {
      ABSL_DCHECK(from._impl_.parent_data_ != nullptr);
      if (_this->_impl_.parent_data_ == nullptr) {
        _this->_impl_.parent_data_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.parent_data_);
      } else {
        _this->_impl_.parent_data_->MergeFrom(*from._impl_.parent_data_);
      }
    }
    if ((cached_has_bits & 0x00000200u) != 0) {
      if (from._internal_serial() != 0) {
        _this->_impl_.serial_ = from._impl_.serial_;
      }
    }
    if ((cached_has_bits & 0x00000400u) != 0) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
    if ((cached_has_bits & 0x00000800u) != 0) {
      if (from._internal_is_ca() != 0) {
        _this->_impl_.is_ca_ = from._impl_.is_ca_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CertData::CopyFrom(const CertData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:license.CertData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CertData::InternalSwap(CertData* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.dns_names_.InternalSwap(&other->_impl_.dns_names_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.organization_, &other->_impl_.organization_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.organizational_unit_, &other->_impl_.organizational_unit_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.country_, &other->_impl_.country_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.locality_, &other->_impl_.locality_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.common_name_, &other->_impl_.common_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.subject_serial_, &other->_impl_.subject_serial_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CertData, _impl_.is_ca_)
      + sizeof(CertData::_impl_.is_ca_)
      - PROTOBUF_FIELD_OFFSET(CertData, _impl_.valid_from_)>(
          reinterpret_cast<char*>(&_impl_.valid_from_),
          reinterpret_cast<char*>(&other->_impl_.valid_from_));
}

::google::protobuf::Metadata CertData::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace license
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_license_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
